const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  adminUsers: "/AdminUsers",
  adminCategories: "/categories",
  adminBooks: "/books",
  adminLogin: "/adminLogin",
  adminOrders: "/adminOrders",
  adminOrdersDetail: "/adminOrders/:id",
  brands: "/brands",
  book: "/books/:id",
  books: "/books",
  cart: "/cartItem",
  logout: "/logout",
  account: "/account",
  address: "/account/address",
  order: "/account/orders",
  favorite: "/account/favorite",
  checkout: "/checkout",
  order: "/account/orders",
  orderDetail: "/account/orders/:id",
};
export default routes;
