const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  adminUsers: "/AdminUsers",
  adminCategories: "/categories",
  adminBooks: "/AdminBooks",
  adminLogin: "/adminLogin",
  adminOrders: "/adminOrders",
  adminPublishers: "/adminPublishers",
  adminAuthors: "/adminAuthors",
  adminOrdersDetail: "/adminOrders/:id",
  adminDiscounts: "/adminDiscounts",
  adminReviews: "/adminReviews",
  adminStatistic: "/adminStatistic",
  adminShipping: "/adminShipping",
  brands: "/brands",
  book: "/books/:id",
  books: "/books",
  cart: "/cartItem",
  logout: "/logout",
  account: "/account",
  address: "/account/address",
  order: "/account/orders",
  favorite: "/account/favorite",
  checkout: "/checkout",
  order: "/account/orders",
  orderDetail: "/account/orders/:id",
  paymentSuccess: "/success",
  contact: "/contact",
};
export default routes;
